In [ ]:
import pandas as pd  
import numpy as np


In [291]:
data_path = 'sensor_readings_24.data'
df = pd.read_csv(data_path)
X = df.iloc[:, :-1].values
print(X)

[[0.438 0.498 3.625 ... 0.444 0.443 0.429]
 [0.438 0.498 3.625 ... 0.444 0.446 0.429]
 [0.437 0.501 3.625 ... 0.444 0.444 0.429]
 ...
 [0.937 5.    4.034 ... 5.    5.    1.105]
 [0.945 4.052 4.052 ... 5.    5.    1.118]
 [0.95  4.066 5.    ... 5.    5.    1.168]]


# Primeira Questão

## Primeiro Metódo

In [292]:
def mcov1(X):
    N, p = X.shape
    m = np.mean(X, axis=0)
    soma = np.zeros((p, p))
    #soma = 0
    for j in range(N):
            aux = X[j, :].reshape(p, 1) - m.reshape(p, 1)
            soma += aux @ aux.T

    C = soma / N
    
    return C

C1 = mcov1(X)
print(C1)

[[ 0.64429378  0.25774343  0.14109919  0.06112554  0.02183335 -0.11725092
  -0.32221198 -0.17313098 -0.3326806  -0.2933401  -0.23037136 -0.23598585
  -0.17755227 -0.27982877 -0.18690922  0.05793543  0.10394279  0.11645266
   0.17023967  0.16622908  0.19983476  0.43077107  0.39652127  0.43242752]
 [ 0.25774343  1.98789812  0.56864023  0.30214911  0.28285058  0.08784358
  -0.10914603 -0.01353742 -0.10068077 -0.17052749 -0.42862975 -0.25911075
  -0.40933036 -0.26393574 -0.14894677 -0.04912134 -0.08585944 -0.04149665
   0.04655638  0.11692279  0.06652167 -0.00402519  0.10491815  0.17001914]
 [ 0.14109919  0.56864023  1.55585663  0.64769991  0.55047114  0.25758459
  -0.12896883 -0.25851141 -0.37231202 -0.29218848 -0.2708856  -0.36619736
  -0.32008489 -0.31900322 -0.28527856 -0.02700165 -0.08124026 -0.11426119
  -0.09074583 -0.00918973 -0.01109068  0.25563067  0.18116124  0.1094225 ]
 [ 0.06112554  0.30214911  0.64769991  1.71431308  1.09880567  0.52951466
  -0.12606044 -0.18621779 -0.300920

## Segundo Metódo

In [293]:
def mcov2(X):
    N, p = X.shape
    m = np.mean(X, axis=0)
    aux = X - m
    C = aux.T @ aux

    return C/N

C2 = mcov2(X)
print(C2)

[[ 0.64429378  0.25774343  0.14109919  0.06112554  0.02183335 -0.11725092
  -0.32221198 -0.17313098 -0.3326806  -0.2933401  -0.23037136 -0.23598585
  -0.17755227 -0.27982877 -0.18690922  0.05793543  0.10394279  0.11645266
   0.17023967  0.16622908  0.19983476  0.43077107  0.39652127  0.43242752]
 [ 0.25774343  1.98789812  0.56864023  0.30214911  0.28285058  0.08784358
  -0.10914603 -0.01353742 -0.10068077 -0.17052749 -0.42862975 -0.25911075
  -0.40933036 -0.26393574 -0.14894677 -0.04912134 -0.08585944 -0.04149665
   0.04655638  0.11692279  0.06652167 -0.00402519  0.10491815  0.17001914]
 [ 0.14109919  0.56864023  1.55585663  0.64769991  0.55047114  0.25758459
  -0.12896883 -0.25851141 -0.37231202 -0.29218848 -0.2708856  -0.36619736
  -0.32008489 -0.31900322 -0.28527856 -0.02700165 -0.08124026 -0.11426119
  -0.09074583 -0.00918973 -0.01109068  0.25563067  0.18116124  0.1094225 ]
 [ 0.06112554  0.30214911  0.64769991  1.71431308  1.09880567  0.52951466
  -0.12606044 -0.18621779 -0.300920

## Terceiro Metódo

In [294]:
def mcov3(X):
    N, p = X.shape
    m = np.mean(X, axis=0)
    R = np.zeros((p, p))
    for j in range (N):
        R = R + X[j, :].reshape(p, 1) @ X[j, :].reshape(p, 1).T
    
    m2 = m.reshape(p,1)
    C = R/N - m2@m2.T
    return C

C3 = mcov3(X)
print(C3)


[[ 0.64429378  0.25774343  0.14109919  0.06112554  0.02183335 -0.11725092
  -0.32221198 -0.17313098 -0.3326806  -0.2933401  -0.23037136 -0.23598585
  -0.17755227 -0.27982877 -0.18690922  0.05793543  0.10394279  0.11645266
   0.17023967  0.16622908  0.19983476  0.43077107  0.39652127  0.43242752]
 [ 0.25774343  1.98789812  0.56864023  0.30214911  0.28285058  0.08784358
  -0.10914603 -0.01353742 -0.10068077 -0.17052749 -0.42862975 -0.25911075
  -0.40933036 -0.26393574 -0.14894677 -0.04912134 -0.08585944 -0.04149665
   0.04655638  0.11692279  0.06652167 -0.00402519  0.10491815  0.17001914]
 [ 0.14109919  0.56864023  1.55585663  0.64769991  0.55047114  0.25758459
  -0.12896883 -0.25851141 -0.37231202 -0.29218848 -0.2708856  -0.36619736
  -0.32008489 -0.31900322 -0.28527856 -0.02700165 -0.08124026 -0.11426119
  -0.09074583 -0.00918973 -0.01109068  0.25563067  0.18116124  0.1094225 ]
 [ 0.06112554  0.30214911  0.64769991  1.71431308  1.09880567  0.52951466
  -0.12606044 -0.18621779 -0.300920

## Quarto Metódo

In [295]:
def mcov4(X):
    N, p = X.shape
    m = np.mean(X, axis=0)
    R = (X.T @ X)/N
    C = R - m.reshape(p,1)@m.reshape(p,1).T
    return C

C4 = mcov4(X)
print(C4)

[[ 0.64429378  0.25774343  0.14109919  0.06112554  0.02183335 -0.11725092
  -0.32221198 -0.17313098 -0.3326806  -0.2933401  -0.23037136 -0.23598585
  -0.17755227 -0.27982877 -0.18690922  0.05793543  0.10394279  0.11645266
   0.17023967  0.16622908  0.19983476  0.43077107  0.39652127  0.43242752]
 [ 0.25774343  1.98789812  0.56864023  0.30214911  0.28285058  0.08784358
  -0.10914603 -0.01353742 -0.10068077 -0.17052749 -0.42862975 -0.25911075
  -0.40933036 -0.26393574 -0.14894677 -0.04912134 -0.08585944 -0.04149665
   0.04655638  0.11692279  0.06652167 -0.00402519  0.10491815  0.17001914]
 [ 0.14109919  0.56864023  1.55585663  0.64769991  0.55047114  0.25758459
  -0.12896883 -0.25851141 -0.37231202 -0.29218848 -0.2708856  -0.36619736
  -0.32008489 -0.31900322 -0.28527856 -0.02700165 -0.08124026 -0.11426119
  -0.09074583 -0.00918973 -0.01109068  0.25563067  0.18116124  0.1094225 ]
 [ 0.06112554  0.30214911  0.64769991  1.71431308  1.09880567  0.52951466
  -0.12606044 -0.18621779 -0.300920

## Função nativa do Python

In [296]:
Cref = np.cov(X, rowvar=False, bias=True)
Cmy = mcov4(X)
E  = Cmy - Cref
print(E)

[[ 5.55111512e-16 -3.33066907e-16  2.41473508e-15  1.17961196e-16
  -1.64798730e-15 -6.52256027e-16  3.88578059e-16 -1.22124533e-15
   1.05471187e-15  1.77635684e-15  6.93889390e-16 -1.38777878e-16
   6.10622664e-16 -2.22044605e-16  5.55111512e-16 -6.93889390e-17
  -1.52655666e-16  1.52655666e-16 -1.66533454e-16 -8.32667268e-17
  -1.94289029e-16 -1.11022302e-16 -2.77555756e-16  3.33066907e-16]
 [-3.33066907e-16  1.99840144e-15  8.88178420e-16 -6.66133815e-16
  -1.99840144e-15 -2.78943535e-15 -3.33066907e-15  1.83880688e-16
   1.42941214e-15  1.55431223e-15  1.16573418e-15  3.33066907e-16
   0.00000000e+00 -6.66133815e-16 -2.22044605e-16  1.24900090e-16
  -1.66533454e-16 -6.03683770e-16  3.19189120e-16  1.38777878e-16
  -6.66133815e-16  2.48932819e-16  2.91433544e-16 -5.82867088e-16]
 [ 2.41473508e-15  8.88178420e-16  1.77635684e-15  4.44089210e-16
  -1.33226763e-15 -9.99200722e-16  4.16333634e-16 -7.77156117e-16
   5.55111512e-17 -6.66133815e-16  9.99200722e-16  9.99200722e-16
   6.661